<?php
/************************************************************************
 * This file is part of Monostax.
 *
 * Monostax – Custom EspoCRM extensions.
 * Copyright (C) 2025 Antonio Moura. All rights reserved.
 * Website: https://www.monostax.ai
 *
 * PROPRIETARY AND CONFIDENTIAL
 ************************************************************************/

declare(strict_types=1);

namespace Espo\Modules\FeatureOAuthEnhanced\Rebuild;

use Espo\Core\Rebuild\RebuildAction;
use Espo\Core\Utils\Log;
use Espo\Entities\OAuthProvider;
use Espo\ORM\EntityManager;

/**
 * Rebuild action to seed the shared Meta (System User) OAuth provider.
 *
 * Unlike the WhatsApp / Lead Ads / Instagram providers, the Meta System User
 * provider does NOT drive a browser authorization-code popup. System User
 * access tokens are generated by an admin (Business Manager UI or the System
 * Users API) and pasted into an OAuthAccount via
 * {@see \Espo\Modules\FeatureOAuthEnhanced\Controllers\MetaSystemUserToken}.
 *
 * The provider still needs to exist so that:
 *   - OAuthAccounts can be linked to it (`provider` discriminator
 *     = `meta-system-user`).
 *   - The Client ID (App ID) + Client Secret are configured once and reused
 *     to validate pasted tokens via Meta's /debug_token endpoint.
 *   - `OAuthProvider::getTokenEndpoint()` resolves (it is used when refreshing
 *     a 60-day token via grant_type=fb_exchange_token, should that be added
 *     later).
 *
 * Does NOT overwrite client_id/client_secret if the provider already exists
 * (those are environment-specific secrets set via the admin UI).
 */
class SeedOAuthProviderMetaSystemUser implements RebuildAction
{
    private const PROVIDER_ID = 'msx_meta_su_01';
    private const PROVIDER_NAME = 'Meta (System User)';
    private const DISCRIMINATOR = 'meta-system-user';

    // graph.facebook.com/oauth/access_token also serves grant_type=fb_exchange_token.
    private const TOKEN_ENDPOINT = 'https://graph.facebook.com/v22.0/oauth/access_token';
    private const AUTHORIZATION_ENDPOINT = 'https://www.facebook.com/v22.0/dialog/oauth';

    public function __construct(
        private EntityManager $entityManager,
        private Log $log,
    ) {}

    public function process(): void
    {
        $this->log->info('FeatureOAuthEnhanced: Seeding OAuth provider for Meta System User...');

        $existing = $this->entityManager
            ->getEntityById(OAuthProvider::ENTITY_TYPE, self::PROVIDER_ID);

        if ($existing) {
            $this->applyCommon($existing);
            $this->entityManager->saveEntity($existing);

            $this->log->info('FeatureOAuthEnhanced: OAuth provider "' . self::PROVIDER_NAME . '" updated.');

            return;
        }

        $provider = $this->entityManager->getNewEntity(OAuthProvider::ENTITY_TYPE);
        $provider->set('id', self::PROVIDER_ID);

        $this->applyCommon($provider);

        $this->entityManager->saveEntity($provider);

        $this->log->info('FeatureOAuthEnhanced: OAuth provider "' . self::PROVIDER_NAME . '" created.');
    }

    private function applyCommon(OAuthProvider $provider): void
    {
        $provider->set('name', self::PROVIDER_NAME);
        $provider->set('provider', self::DISCRIMINATOR);
        $provider->set('isActive', true);
        $provider->set('isGloballyShared', true);
        $provider->set('authorizationEndpoint', self::AUTHORIZATION_ENDPOINT);
        $provider->set('tokenEndpoint', self::TOKEN_ENDPOINT);
    }
}
