{{#if failed}}<div class="alert alert-warning" role="alert">{{translate 'detailUnavailable' scope='AiUsage'}}</div>{{else}}
<div class="au-detail-body">
    <div class="au-eyebrow">{{date}}</div><h3>{{kind}}</h3>
    <dl class="au-detail-list">{{#each records}}<dt>{{label}}</dt><dd><a href="{{href}}" target="_blank" rel="noopener noreferrer">{{name}} <span class="fas fa-external-link-alt" aria-hidden="true"></span></a></dd>{{/each}}<dt>{{translate 'action' scope='AiUsage'}}</dt><dd>{{actions}}</dd><dt>{{translate 'billingStatus' scope='AiUsage'}}</dt><dd title="{{billingHint}}">{{billingText}}</dd></dl>
    {{#if group}}<section class="au-group"><h4>{{translate 'billingGroup' scope='AiUsage'}}</h4><p class="text-muted">{{translate 'groupExplanation' scope='AiUsage'}}</p><dl class="au-detail-list"><dt>{{translate 'date' scope='AiUsage'}}</dt><dd>{{group.day}}</dd><dt>{{translate 'engagements' scope='AiUsage'}}</dt><dd>{{group.runs}}</dd><dt>{{translate 'billingUnits' scope='AiUsage'}}</dt><dd>{{group.consumed}}</dd><dt>{{translate 'covered' scope='AiUsage'}}</dt><dd>{{group.covered}}</dd><dt>{{translate 'overage' scope='AiUsage'}}</dt><dd>{{group.overage}}</dd><dt>{{translate 'charges' scope='AiUsage'}}</dt><dd>{{group.charges}}</dd></dl></section>{{/if}}
    <details class="au-explanation"><summary>{{translate 'technicalDetails' scope='AiUsage'}}</summary>{{#unless metered}}<p class="text-muted">{{translate 'legacyTelemetry' scope='AiUsage'}}</p>{{/unless}}<dl class="au-detail-list"><dt>{{translate 'model' scope='AiUsage'}}</dt><dd>{{model}}</dd><dt>{{translate 'providerRequests' scope='AiUsage'}}</dt><dd>{{requests}}</dd>{{#if showTokenUsage}}<dt>{{translate 'inputTokens' scope='AiUsage'}}</dt><dd>{{input}}</dd><dt>{{translate 'outputTokens' scope='AiUsage'}}</dt><dd>{{output}}</dd><dt>{{translate 'cachedTokens' scope='AiUsage'}}</dt><dd>{{cached}}</dd>{{/if}}<dt>{{translate 'duration' scope='AiUsage'}}</dt><dd>{{duration}}</dd></dl></details>
    {{#if showTokenUsage}}{{#if analytics}}<section class="au-group"><h4>{{translate 'internalAnalytics' scope='AiUsage'}}</h4>
        <dl class="au-detail-list">{{#each analytics.cards}}<dt>{{label}}</dt><dd>{{value}}</dd>{{/each}}</dl>
        <p class="au-footnote text-muted">{{translate 'tokenAccountingHint' scope='AiUsage'}}</p>
        <p class="au-footnote text-muted">{{translate 'cacheAccountingHint' scope='AiUsage'}}</p>
        <details class="au-explanation"><summary>{{translate 'efficiencyAndCoverage' scope='AiUsage'}}</summary><dl class="au-detail-list">{{#each analytics.diagnostics}}<dt>{{label}}</dt><dd>{{value}}</dd>{{/each}}</dl><p class="text-muted">{{translate 'analyticsCoverageHint' scope='AiUsage'}}</p></details>
        <details class="au-explanation"><summary>{{translate 'analyticsSources' scope='AiUsage'}}</summary><p class="text-muted">{{translate 'sourceAccountingHint' scope='AiUsage'}}</p>{{#each analytics.sources}}<h4>{{label}}</h4><dl class="au-detail-list">{{#each metrics}}<dt>{{label}}</dt><dd>{{value}}</dd>{{/each}}</dl>{{/each}}</details>
    </section>{{/if}}{{/if}}
</div>
{{/if}}
